---
title: "Scotland's Heath: The Drug Crisis"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Names of group members

Tom, Lee and Melanie

### Roles & responsibilities of each member

**Tom** worked on life expectancy clean up, alcohol visualisations

**Lee** worked on drug clean up and visualisations

**Melanie** worked on alcohol clean up and life expectancy visualisations

**Everyone** worked on ...

### Brief description of dashboard topic

Our dashboard contains ...

Our health topic is ...

The dashboard outlines our health topic in terms of ...

### Stages of the project

* Planning & dashboard wireframe
* Git branching & version control
* Choosing datasets

and so on ...

### Which tools were used in the project

* Zoom (daily stand-ups and occasional mob programming)
* Trello (planning & task allocation)
* Git/GitHub (collaboration & version control)

and so on ...

### How did you gather and synthesise requirements for the project?

We synthesised the information given in the brief by ...

We prioritised ...

### Motivations for using the data you have chosen

We used the dataset on ... to answer ... and because it was ...

### Data quality and potential bias, including a brief summary of data cleaning and transformations

According to the About tab on the dataset page/dedicated page online, the data quality ...

The dataset may/may not be biased because ...

To clean the datasets we ...

### How is the data on statistics.gov.scot stored and structured

[**Hint**: This page offers a good starting point for understanding the data structure: https://guides.statistics.gov.scot/article/34-understanding-the-data-structure]

The data on statistics.gov.scot is in the form of ...

This means ...

Benefits of storing the data like this are ...

### Ethical and legal considerations of the data

[**Hint:** this page contains information on the Open Government License which covers most datasets on statistics.gov.scot: http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/]

There are no/There may be ethical considerations, because ...

The datasets are covered by the Open Government License, which means ...